// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Appearance {
  id: string;
  slug: string | null;
  status: string;
  header_variant?: "classic" | "centered" | "minimal" | "transparent" | "inverse" | "two-row" | "pill" | "compact" | "cta-prominent" | "gradient";
  footer_variant?: "columns" | "simple" | "cta" | "newsletter" | "map" | "mega" | "centered" | "hours" | "social" | "bar";
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Business {
  id: string;
  slug: string | null;
  status: string;
  phone?: string;
  email?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  license?: string;
  gbp_url?: string;
  hours?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Faq {
  id: string;
  slug: string | null;
  status: string;
  question: string;
  answer: string;
  order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  demo?: boolean;
  structured_data?: unknown;
  sections: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  date?: string;
  featured?: boolean;
  body?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Pricing {
  id: string;
  slug: string | null;
  status: string;
  value?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Review {
  id: string;
  slug: string | null;
  status: string;
  author: string;
  rating?: number;
  body?: string;
  date?: string;
  location?: string;
  featured?: boolean;
  source?: "Google" | "Facebook" | "Yelp" | "Direct";
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface ServiceArea {
  id: string;
  slug: string | null;
  status: string;
  city: string;
  state?: string;
  county?: string;
  featured?: boolean;
  order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface ServiceCategory {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  icon?: string;
  order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Service {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  meta_title?: string;
  meta_description?: string;
  image?: string;
  category?: string;
  content?: string;
  is_emergency?: boolean;
  featured?: boolean;
  order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    appearance: Appearance;
    business: Business;
    faqs: Faq;
    pages: Page;
    posts: Post;
    pricing: Pricing;
    reviews: Review;
    service_areas: ServiceArea;
    service_categories: ServiceCategory;
    services: Service;
  }
}